version: 2

sources:
  - name: ecomm
    database: raw
    tables:
      - name: customers
        description: Each record in this table represents a customer in our ecommerce application.
        columns:
          - name: id
            description: '{{ doc("customer_id") }}'
      - name: orders_us
        description: Each record in this table represents an order in our ecommerce store in the US
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: orders_de
        description: Each record in this table represents an order in our ecommerce store in Germany
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: orders_au
        description: Each record in this table represents an order in our ecommerce store in Australia
        columns:
          - name: id
            tests:
              - unique:
                  severity: warn
              - not_null
      - name: deliveries
        description: Each record in this table represents an order delivery in our ecommerce application.

  - name: sheets
    database: raw
    tables:
      - name: customer_survey_responses

  - name: stripe
    database: raw
    tables:
      - name: payments
  
  - name: geo
    database: raw
    tables:
      - name: countries